# Generated by Django 3.0.2 on 2020-01-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('constraint_field1', models.CharField(max_length=50)),
                ('constraint_field2', models.CharField(max_length=50, null=True)),
                ('field3', models.TextField(null=True)),
            ],
            options={
                'db_table': 'arigato',
            },
        ),
        migrations.CreateModel(
            name='MyModelWithConstraint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('constraint_field1', models.CharField(max_length=50)),
                ('constraint_field2', models.CharField(max_length=50, null=True)),
                ('field3', models.TextField(null=True)),
            ],
            options={
                'db_table': 'bokunopico',
            },
        ),
        migrations.AddConstraint(
            model_name='mymodelwithconstraint',
            constraint=models.UniqueConstraint(fields=('constraint_field1', 'constraint_field2'), name='constraint_fields'),
        ),
    ]
