# Generated by Django 3.0.2 on 2020-01-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_message_id', models.CharField(max_length=50, null=True)),
                ('text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'arigato',
            },
        ),
        migrations.CreateModel(
            name='MyModelWithConstraint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_message_id', models.CharField(max_length=50, null=True)),
                ('text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'bokunopico',
            },
        ),
        migrations.AddConstraint(
            model_name='mymodelwithconstraint',
            constraint=models.UniqueConstraint(fields=('source', 'source_message_id'), name='messages_source_source_message_id_key'),
        ),
    ]
